--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buffets_buffet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.buffets_buffet (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    address text NOT NULL,
    is_temporarily_closed boolean NOT NULL,
    image_url character varying(200)
);


ALTER TABLE public.buffets_buffet OWNER TO postgres;

--
-- Name: buffets_buffet_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.buffets_buffet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buffets_buffet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buffets_food; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.buffets_food (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    price_student numeric(6,2) NOT NULL,
    price_employee numeric(6,2) NOT NULL,
    price_guest numeric(6,2) NOT NULL,
    category character varying(100) NOT NULL,
    is_available boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    buffet_id bigint NOT NULL
);


ALTER TABLE public.buffets_food OWNER TO postgres;

--
-- Name: buffets_food_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.buffets_food ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buffets_food_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buffets_openinghours; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.buffets_openinghours (
    id bigint NOT NULL,
    day integer NOT NULL,
    open_time time without time zone,
    close_time time without time zone,
    is_closed boolean NOT NULL,
    buffet_id bigint NOT NULL
);


ALTER TABLE public.buffets_openinghours OWNER TO postgres;

--
-- Name: buffets_openinghours_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.buffets_openinghours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buffets_openinghours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dashboard_news; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dashboard_news (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    date timestamp with time zone NOT NULL
);


ALTER TABLE public.dashboard_news OWNER TO postgres;

--
-- Name: dashboard_news_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dashboard_news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dashboard_news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: schedules_course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schedules_course (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    code character varying(20) NOT NULL,
    credits integer NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.schedules_course OWNER TO postgres;

--
-- Name: schedules_course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.schedules_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedules_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedules_lesson; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schedules_lesson (
    id bigint NOT NULL,
    lesson_type character varying(20) NOT NULL,
    lecturer character varying(100) NOT NULL,
    room character varying(50) NOT NULL,
    day_of_week integer NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.schedules_lesson OWNER TO postgres;

--
-- Name: schedules_lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.schedules_lesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedules_lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedules_schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schedules_schedule (
    id bigint NOT NULL,
    lesson_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.schedules_schedule OWNER TO postgres;

--
-- Name: schedules_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.schedules_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedules_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: studybuddy_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.studybuddy_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    full_name character varying(255) NOT NULL,
    phone character varying(20),
    practice_group character varying(50) NOT NULL,
    is_teacher boolean NOT NULL
);


ALTER TABLE public.studybuddy_user OWNER TO postgres;

--
-- Name: studybuddy_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.studybuddy_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.studybuddy_user_groups OWNER TO postgres;

--
-- Name: studybuddy_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.studybuddy_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.studybuddy_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: studybuddy_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.studybuddy_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.studybuddy_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: studybuddy_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.studybuddy_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.studybuddy_user_user_permissions OWNER TO postgres;

--
-- Name: studybuddy_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.studybuddy_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.studybuddy_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add buffet	7	add_buffet
26	Can change buffet	7	change_buffet
27	Can delete buffet	7	delete_buffet
28	Can view buffet	7	view_buffet
29	Can add food	8	add_food
30	Can change food	8	change_food
31	Can delete food	8	delete_food
32	Can view food	8	view_food
33	Can add opening hours	9	add_openinghours
34	Can change opening hours	9	change_openinghours
35	Can delete opening hours	9	delete_openinghours
36	Can view opening hours	9	view_openinghours
37	Can add News	10	add_news
38	Can change News	10	change_news
39	Can delete News	10	delete_news
40	Can view News	10	view_news
41	Can add Course	11	add_course
42	Can change Course	11	change_course
43	Can delete Course	11	delete_course
44	Can view Course	11	view_course
45	Can add schedule	12	add_schedule
46	Can change schedule	12	change_schedule
47	Can delete schedule	12	delete_schedule
48	Can view schedule	12	view_schedule
49	Can add Lesson	13	add_lesson
50	Can change Lesson	13	change_lesson
51	Can delete Lesson	13	delete_lesson
52	Can view Lesson	13	view_lesson
\.


--
-- Data for Name: buffets_buffet; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.buffets_buffet (id, name, address, is_temporarily_closed, image_url) FROM stdin;
\.


--
-- Data for Name: buffets_food; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.buffets_food (id, name, description, price_student, price_employee, price_guest, category, is_available, created_at, buffet_id) FROM stdin;
\.


--
-- Data for Name: buffets_openinghours; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.buffets_openinghours (id, day, open_time, close_time, is_closed, buffet_id) FROM stdin;
\.


--
-- Data for Name: dashboard_news; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dashboard_news (id, title, content, date) FROM stdin;
1	МЕЖФАКУЛЬТЕТСКИЙ ЧЕМПИОНАТ КБТУ ПО ШАХМАТАМ	Анонсируем самый массовый внутренний шахматный турнир учебного года – межфакультетский чемпионат КБТУ среди студентов и магистрантов. Он начнётся в среду, 8 апреля в 17:30 в шахматном клубе (Jastar City, актовый зал). Состав команды – трое юношей и одна девушка. За команду могут играть только представители одного и того же факультета/школы.\r\n\r\nКаждый факультет/школа может выставить любое количество команд. Просим (потенциальных) капитанов сформировать свои будущие команды и незадолго до начала турнира представить заявки (и игроков, естественно) в шахматный клуб. Приглашаем и зрителей	2026-04-16 21:30:05.835+00
2	Приглашение на городской спортивный турнир «ALMA CUP 2026»	Уважаемые студенты!\r\n\r\nПриглашаем вас принять участие в городском спортивном турнире «ALMA CUP 2026», проводимом при поддержке Управления молодежной политики города Алматы.\r\n\r\nТурнир является комплексным мероприятием и включает соревнования по следующему виду спорта:\r\n\r\nлёгкая атлетика\r\nМероприятие направлено на развитие массового спорта, укрепление командного духа и популяризацию здорового образа жизни среди молодежи.	2026-04-16 21:33:05.713+00
3	Grab a Book	You’re invited to Grab a Book — a free book giveaway organized by the Scientific Library Nurly Aqyl. \r\n✨ Already tomorrow! \r\nThe event will take place in an interactive game format. You will move through different stations, complete simple but engaging challenges, and earn tokens for each task. These tokens can then be exchanged for books — so the more stations you pass, the more books you can take home. \r\nIt’s not just a giveaway, but a full experience: you’ll explore, play, interact, and collect your rewards along the way. \r\nYou will also have a chance to win various prizes, plus enjoy some snacks during the event. The atmosphere is inspired by Stranger Things - we’re waiting for you in the Upside Down 👀 \r\n📅 April 16 \r\n🕙 From 10:00 AM \r\n📍 Foyer of the Scientific Library Nurly Aqyl	2026-04-16 21:33:41.669+00
4	XCHANGE	Entry by list only\r\nRegistration via manager\r\n📩 Telegram: @ded_vnr – Azhar\r\n\r\nXCHANGE – an intellectual event in TEDx format\r\n\r\nTheme: “Tolyq Adam”\r\n\r\nSpeakers from blogging, law, investment, economics, and education\r\n\r\nWhat to expect:\r\n🎤 talks & insights\r\n🎶 live music\r\n☕️ coffee break\r\n🍽 food from sponsors\r\n🎁 giveaways\r\n📸 photo booth\r\n\r\n📅 April 17\r\n📍 Independence Hall\r\n🕔 17:00\r\n\r\nLimited seats – register in advance and bring your friends 🙌	2026-04-19 15:53:57.484+00
5	🌸 CRYSTAL PRESENTS💎 ANIME QUIZ	Предлагаем вам окунуться в мир аниме и проверить свои знания! Действительно ли вы знаете своих любимых персонажей?\r\n\r\nСоберите команду от 2 до 9 человек и приходите на наш вечер! Вас ждут интересные вопросы, классная атмосфера, приятное времяпровождение и крутые призы 🎁\r\n\r\n📅 16 апреля\r\n🏛️ КБТУ, 726 кабинет\r\n⏰ 19:00\r\n💰 Билет: 800 тг\r\n\r\n⚡️ Места ограничены - успейте занять место, потом мест не будет!\r\n\r\n🎟 Билеты: \r\n@muhaamedzhannn \r\n@theleol \r\n@zha555eka	2026-04-19 15:55:12.369+00
6	🎶 TUMAR TUNES – a unique musical evening!	🎁 Win a ticket to the NE PROSTO ORCHESTRA concert!\r\n\r\nWe invite you to an evening filled with live music, a special atmosphere, and vibrant student energy!\r\n\r\n📅 Date: April 3, 2026\r\n⏰ Time: 18:00\r\n📍 Venue: KBTU, Independence Hall\r\n🎟 Ticket price: 1500 KZT\r\n\r\n✨ What awaits you:\r\n• Popular soundtracks from movies and TV series\r\n• Kazakh traditional kui in a unique rock interpretation\r\n• Famous songs – sing-along hits\r\n\r\n🌟 Also featuring:\r\n• Special guest stars\r\n• Guests from: SDU, AUES, UIB, KazGASA, Narxoz\r\n\r\nThis night is a true celebration of music, culture, and student spirit! 🎉\r\n\r\n⚠️ Limited tickets available – don’t miss out!\r\n\r\n📲 For tickets:\r\n• Telegram: @aiigganym | WhatsApp: +7 776 529 0063\r\n• Telegram: @adletzk | WhatsApp: +7 708 392 8349	2026-04-19 15:56:00.979+00
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-16 21:30:05.838+00	1	МЕЖФАКУЛЬТЕТСКИЙ ЧЕМПИОНАТ КБТУ ПО ШАХМАТАМ	1	[{"added": {}}]	10	1
2	2026-04-16 21:33:05.717+00	2	Приглашение на городской спортивный турнир «ALMA CUP 2026»	1	[{"added": {}}]	10	1
3	2026-04-16 21:33:41.672+00	3	Grab a Book	1	[{"added": {}}]	10	1
4	2026-04-19 15:53:57.49+00	4	XCHANGE	1	[{"added": {}}]	10	1
5	2026-04-19 15:55:12.377+00	5	🌸 CRYSTAL PRESENTS💎 ANIME QUIZ	1	[{"added": {}}]	10	1
6	2026-04-19 15:56:00.984+00	6	🎶 TUMAR TUNES – a unique musical evening!	1	[{"added": {}}]	10	1
7	2026-04-20 09:26:23.326683+00	1	INFT2205: Web Development	1	[{"added": {}}]	11	1
8	2026-04-21 08:00:32.735245+00	1	INFT3210: Field Projects for Information Systems	1	[{"added": {}}, {"added": {"name": "Lesson", "object": "INFT3210 - Lecture (Tuesday)"}}]	11	1
9	2026-04-21 08:07:33.069626+00	2	INFT2205: Web Development	1	[{"added": {}}, {"added": {"name": "Lesson", "object": "INFT2205 - Lecture (Monday)"}}, {"added": {"name": "Lesson", "object": "INFT2205 - Practice (Thursday)"}}]	11	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	studybuddy	user
7	buffets	buffet
8	buffets	food
9	buffets	openinghours
10	dashboard	news
11	schedules	course
12	schedules	schedule
13	schedules	lesson
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-20 08:19:41.132972+00
2	contenttypes	0002_remove_content_type_name	2026-04-20 08:19:41.149622+00
3	auth	0001_initial	2026-04-20 08:19:41.21735+00
4	auth	0002_alter_permission_name_max_length	2026-04-20 08:19:41.223388+00
5	auth	0003_alter_user_email_max_length	2026-04-20 08:19:41.228466+00
6	auth	0004_alter_user_username_opts	2026-04-20 08:19:41.232402+00
7	auth	0005_alter_user_last_login_null	2026-04-20 08:19:41.237439+00
8	auth	0006_require_contenttypes_0002	2026-04-20 08:19:41.239933+00
9	auth	0007_alter_validators_add_error_messages	2026-04-20 08:19:41.245291+00
10	auth	0008_alter_user_username_max_length	2026-04-20 08:19:41.250291+00
11	auth	0009_alter_user_last_name_max_length	2026-04-20 08:19:41.257647+00
12	auth	0010_alter_group_name_max_length	2026-04-20 08:19:41.270629+00
13	auth	0011_update_proxy_permissions	2026-04-20 08:19:41.277627+00
14	auth	0012_alter_user_first_name_max_length	2026-04-20 08:19:41.282625+00
15	studybuddy	0001_initial	2026-04-20 08:19:41.335516+00
16	admin	0001_initial	2026-04-20 08:19:41.365528+00
17	admin	0002_logentry_remove_auto_add	2026-04-20 08:19:41.37486+00
18	admin	0003_logentry_add_action_flag_choices	2026-04-20 08:19:41.382354+00
19	buffets	0001_initial	2026-04-20 08:19:41.424678+00
20	dashboard	0001_initial	2026-04-20 08:19:41.435744+00
22	sessions	0001_initial	2026-04-20 08:19:41.498433+00
23	schedules	0001_initial	2026-04-21 07:58:56.939845+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
kdlpzhaxdg9q2n1pwowi0u2mi1s38yv5	.eJxVjMEOwiAQRP-FsyFQILAevfsNZIFdqRqalPbU-O-2SQ96m8x7M5uIuC41rp3mOBZxFVpcfruE-UXtAOWJ7THJPLVlHpM8FHnSLu9TofftdP8OKva6rwkBtEnOGyCtbVBGIZREoTBwAmuZQrZeIZOjwK54B4Nh2lMatGXx-QLr8TiD:1wEjuT:7VGResCtYLSgEn1MOZ29quL3LNWXC4m1SjxLv-1h4d0	2026-05-04 08:23:13.727095+00
inwlavjp2275x8lac0e8i2iphzmn8fpf	.eJxVjMEOwiAQRP-FsyFQILAevfsNZIFdqRqalPbU-O-2SQ96m8x7M5uIuC41rp3mOBZxFVpcfruE-UXtAOWJ7THJPLVlHpM8FHnSLu9TofftdP8OKva6rwkBtEnOGyCtbVBGIZREoTBwAmuZQrZeIZOjwK54B4Nh2lMatGXx-QLr8TiD:1wEk8i:fLCkQv_8WgctVL-1iY8io3LUYuVMurrhlI9qIjVwwiY	2026-05-04 08:37:56.320117+00
1hone5cnfkpx403gsftsgo4rv601rg2k	.eJxVjMsOwiAUBf-FtSE8pAWX7vsN5D5AqgaS0q6M_65NutDtmZnzEhG2tcStpyXOLC5Ci9PvhkCPVHfAd6i3JqnVdZlR7oo8aJdT4_S8Hu7fQYFevrULSmnrSeuElJMBFYhMQGYIGkY7EIfh7Dxmi56tR00jGoMqW-uCUeL9AeysN_A:1wEk0m:R5JL3I7dM3sogS-ucDsMZ3VYQc-XCxlAjvjPPc8SLVw	2026-05-04 08:29:44.972+00
fnjp3mp9fb4ix4iaby0q2c6elyi1owbg	.eJxVjMsOwiAUBf-FtSE8pAWX7vsN5D5AqgaS0q6M_65NutDtmZnzEhG2tcStpyXOLC5Ci9PvhkCPVHfAd6i3JqnVdZlR7oo8aJdT4_S8Hu7fQYFevrULSmnrSeuElJMBFYhMQGYIGkY7EIfh7Dxmi56tR00jGoMqW-uCUeL9AeysN_A:1wEUMh:W02ZxCJT_PDYwzh2YRXPtLW-MKuaHGtSvn9gY34eUb8	2026-05-03 15:47:19.005+00
tg88mq6y5w142u27jmsrhb10ctryzub2	.eJxVjMsOwiAUBf-FtSE8pAWX7vsN5D5AqgaS0q6M_65NutDtmZnzEhG2tcStpyXOLC5Ci9PvhkCPVHfAd6i3JqnVdZlR7oo8aJdT4_S8Hu7fQYFevrULSmnrSeuElJMBFYhMQGYIGkY7EIfh7Dxmi56tR00jGoMqW-uCUeL9AeysN_A:1wDOWb:Jh26cRyT4DzyL0lexOVd_0KyGAoVtV7oGWBTKxXjkMY	2026-04-30 15:21:01.596+00
cg2jq2c0ap5vk26o6y0td4u19omjadiy	.eJxVjMsOwiAUBf-FtSE8pAWX7vsN5D5AqgaS0q6M_65NutDtmZnzEhG2tcStpyXOLC5Ci9PvhkCPVHfAd6i3JqnVdZlR7oo8aJdT4_S8Hu7fQYFevrULSmnrSeuElJMBFYhMQGYIGkY7EIfh7Dxmi56tR00jGoMqW-uCUeL9AeysN_A:1wEkGj:plKZURF77f907O-qGu-ycQYmACbtF0kRWfw3dlNNb6E	2026-05-04 08:46:13.891459+00
\.


--
-- Data for Name: schedules_course; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.schedules_course (id, name, code, credits, description) FROM stdin;
1	Field Projects for Information Systems	INFT3210	5	This course is a practice - oriented .  project based discipline focused on real - world Information Systems problems in organizational settings .  Students work individually and in teams to conduct field investigations , collect and analyze qualitative and quantitative data , and design feasible IS solutions .  The course integrates : .  Interpretive user research ( interviews , open and axial coding ) Survey research and basic statistical analysis Qualitative Comparative Analysis ( QCA ) for configurational reasoning Evaluation of traditional ML .  systems using precision , recall , and related metrics to solve real life problems Students frame problems using variance , process , and systems analysis from Information Systems theory perspectives , ensuring analytical rigor while maintaining strong practical relevance .
2	Web Development	INFT2205	6	This course provides a practical introduction to modern web development using Angular for the client side and Django for the server side. Angular is a platform and framework for building single-page client applications using HTML and TypeScript. Django is a high-level Python web framework that promotes rapid development and clean, pragmatic design.\r\nThrough hands-on projects and lab assignments, students will gain experience building full-stack web applications. The course focuses on the practical use of Angular and Django in solving real-world problems, with an emphasis on code quality, scalability, and industry best practices.
\.


--
-- Data for Name: schedules_lesson; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.schedules_lesson (id, lesson_type, lecturer, room, day_of_week, start_time, end_time, course_id) FROM stdin;
1	lecture	Smaiyl A.	Independence hall	2	10:00:00	13:00:00	1
2	lecture	Saimassayeva S.	336	1	13:00:00	15:00:00	2
3	practice	Saimassayeva S.	438	4	12:00:00	14:00:00	2
\.


--
-- Data for Name: schedules_schedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.schedules_schedule (id, lesson_id, student_id) FROM stdin;
\.


--
-- Data for Name: studybuddy_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.studybuddy_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, full_name, phone, practice_group, is_teacher) FROM stdin;
1	pbkdf2_sha256$1200000$nND2kvp1oMvoeSNkTLP9eC$AYG2eZtCspEHZLOTrcsU85eAicaTOdrsl1tNS/JDimM=	2026-04-20 08:46:13.887305+00	t	kamila			kamila@gmail.com	t	t	2026-04-16 15:19:00.566+00		\N		f
\.


--
-- Data for Name: studybuddy_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.studybuddy_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: studybuddy_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.studybuddy_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: buffets_buffet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.buffets_buffet_id_seq', 1, false);


--
-- Name: buffets_food_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.buffets_food_id_seq', 1, false);


--
-- Name: buffets_openinghours_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.buffets_openinghours_id_seq', 1, false);


--
-- Name: dashboard_news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dashboard_news_id_seq', 6, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 9, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 23, true);


--
-- Name: schedules_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.schedules_course_id_seq', 2, true);


--
-- Name: schedules_lesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.schedules_lesson_id_seq', 3, true);


--
-- Name: schedules_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.schedules_schedule_id_seq', 1, false);


--
-- Name: studybuddy_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.studybuddy_user_groups_id_seq', 1, false);


--
-- Name: studybuddy_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.studybuddy_user_id_seq', 1, true);


--
-- Name: studybuddy_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.studybuddy_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: buffets_buffet buffets_buffet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buffets_buffet
    ADD CONSTRAINT buffets_buffet_pkey PRIMARY KEY (id);


--
-- Name: buffets_food buffets_food_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buffets_food
    ADD CONSTRAINT buffets_food_pkey PRIMARY KEY (id);


--
-- Name: buffets_openinghours buffets_openinghours_buffet_id_day_b5db3f48_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buffets_openinghours
    ADD CONSTRAINT buffets_openinghours_buffet_id_day_b5db3f48_uniq UNIQUE (buffet_id, day);


--
-- Name: buffets_openinghours buffets_openinghours_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buffets_openinghours
    ADD CONSTRAINT buffets_openinghours_pkey PRIMARY KEY (id);


--
-- Name: dashboard_news dashboard_news_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dashboard_news
    ADD CONSTRAINT dashboard_news_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: schedules_course schedules_course_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules_course
    ADD CONSTRAINT schedules_course_code_key UNIQUE (code);


--
-- Name: schedules_course schedules_course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules_course
    ADD CONSTRAINT schedules_course_pkey PRIMARY KEY (id);


--
-- Name: schedules_lesson schedules_lesson_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules_lesson
    ADD CONSTRAINT schedules_lesson_pkey PRIMARY KEY (id);


--
-- Name: schedules_schedule schedules_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules_schedule
    ADD CONSTRAINT schedules_schedule_pkey PRIMARY KEY (id);


--
-- Name: schedules_schedule schedules_schedule_student_id_lesson_id_7e2e6848_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules_schedule
    ADD CONSTRAINT schedules_schedule_student_id_lesson_id_7e2e6848_uniq UNIQUE (student_id, lesson_id);


--
-- Name: studybuddy_user_groups studybuddy_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user_groups
    ADD CONSTRAINT studybuddy_user_groups_pkey PRIMARY KEY (id);


--
-- Name: studybuddy_user_groups studybuddy_user_groups_user_id_group_id_6fef6934_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user_groups
    ADD CONSTRAINT studybuddy_user_groups_user_id_group_id_6fef6934_uniq UNIQUE (user_id, group_id);


--
-- Name: studybuddy_user studybuddy_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user
    ADD CONSTRAINT studybuddy_user_pkey PRIMARY KEY (id);


--
-- Name: studybuddy_user_user_permissions studybuddy_user_user_per_user_id_permission_id_9ed75b94_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user_user_permissions
    ADD CONSTRAINT studybuddy_user_user_per_user_id_permission_id_9ed75b94_uniq UNIQUE (user_id, permission_id);


--
-- Name: studybuddy_user_user_permissions studybuddy_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user_user_permissions
    ADD CONSTRAINT studybuddy_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: studybuddy_user studybuddy_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user
    ADD CONSTRAINT studybuddy_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: buffets_food_buffet_id_36e7b4f8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX buffets_food_buffet_id_36e7b4f8 ON public.buffets_food USING btree (buffet_id);


--
-- Name: buffets_openinghours_buffet_id_50e9854a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX buffets_openinghours_buffet_id_50e9854a ON public.buffets_openinghours USING btree (buffet_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: schedules_course_code_a40f5000_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX schedules_course_code_a40f5000_like ON public.schedules_course USING btree (code varchar_pattern_ops);


--
-- Name: schedules_lesson_course_id_89086e07; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX schedules_lesson_course_id_89086e07 ON public.schedules_lesson USING btree (course_id);


--
-- Name: schedules_schedule_lesson_id_7583d44f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX schedules_schedule_lesson_id_7583d44f ON public.schedules_schedule USING btree (lesson_id);


--
-- Name: schedules_schedule_student_id_392146cd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX schedules_schedule_student_id_392146cd ON public.schedules_schedule USING btree (student_id);


--
-- Name: studybuddy_user_groups_group_id_cd2cd352; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX studybuddy_user_groups_group_id_cd2cd352 ON public.studybuddy_user_groups USING btree (group_id);


--
-- Name: studybuddy_user_groups_user_id_8c616692; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX studybuddy_user_groups_user_id_8c616692 ON public.studybuddy_user_groups USING btree (user_id);


--
-- Name: studybuddy_user_user_permissions_permission_id_aefd9735; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX studybuddy_user_user_permissions_permission_id_aefd9735 ON public.studybuddy_user_user_permissions USING btree (permission_id);


--
-- Name: studybuddy_user_user_permissions_user_id_41928f4e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX studybuddy_user_user_permissions_user_id_41928f4e ON public.studybuddy_user_user_permissions USING btree (user_id);


--
-- Name: studybuddy_user_username_ab2810ea_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX studybuddy_user_username_ab2810ea_like ON public.studybuddy_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: buffets_food buffets_food_buffet_id_36e7b4f8_fk_buffets_buffet_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buffets_food
    ADD CONSTRAINT buffets_food_buffet_id_36e7b4f8_fk_buffets_buffet_id FOREIGN KEY (buffet_id) REFERENCES public.buffets_buffet(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: buffets_openinghours buffets_openinghours_buffet_id_50e9854a_fk_buffets_buffet_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buffets_openinghours
    ADD CONSTRAINT buffets_openinghours_buffet_id_50e9854a_fk_buffets_buffet_id FOREIGN KEY (buffet_id) REFERENCES public.buffets_buffet(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_studybuddy_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_studybuddy_user_id FOREIGN KEY (user_id) REFERENCES public.studybuddy_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedules_lesson schedules_lesson_course_id_89086e07_fk_schedules_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules_lesson
    ADD CONSTRAINT schedules_lesson_course_id_89086e07_fk_schedules_course_id FOREIGN KEY (course_id) REFERENCES public.schedules_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedules_schedule schedules_schedule_lesson_id_7583d44f_fk_schedules_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules_schedule
    ADD CONSTRAINT schedules_schedule_lesson_id_7583d44f_fk_schedules_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.schedules_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: schedules_schedule schedules_schedule_student_id_392146cd_fk_studybuddy_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules_schedule
    ADD CONSTRAINT schedules_schedule_student_id_392146cd_fk_studybuddy_user_id FOREIGN KEY (student_id) REFERENCES public.studybuddy_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: studybuddy_user_groups studybuddy_user_groups_group_id_cd2cd352_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user_groups
    ADD CONSTRAINT studybuddy_user_groups_group_id_cd2cd352_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: studybuddy_user_groups studybuddy_user_groups_user_id_8c616692_fk_studybuddy_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user_groups
    ADD CONSTRAINT studybuddy_user_groups_user_id_8c616692_fk_studybuddy_user_id FOREIGN KEY (user_id) REFERENCES public.studybuddy_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: studybuddy_user_user_permissions studybuddy_user_user_permission_id_aefd9735_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user_user_permissions
    ADD CONSTRAINT studybuddy_user_user_permission_id_aefd9735_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: studybuddy_user_user_permissions studybuddy_user_user_user_id_41928f4e_fk_studybudd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.studybuddy_user_user_permissions
    ADD CONSTRAINT studybuddy_user_user_user_id_41928f4e_fk_studybudd FOREIGN KEY (user_id) REFERENCES public.studybuddy_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

