# Generated by Django 6.0.4 on 2026-04-15 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buffet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_temporarily_closed', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_student', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_employee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_guest', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(blank=True, default='Hi. jídlo', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buffet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='buffets.buffet')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('buffet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='buffets.buffet')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('buffet', 'day')},
            },
        ),
    ]
