# Generated by Django 6.0.4 on 2026-04-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buffets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buffet',
            name='image_url',
        ),
    ]
